import { useMemo } from "react";
import { compareTwoStrings } from "string-similarity";

const prohibitedClasses = new Set([
  "Beverages",
  "Bike & E-Bike",
  "Butane & LPG",
  "Canned & Packaged Food",
  "Cosmetics Products",
  "Everyday Clothing",
  "Explosive",
  "Firearms",
  "Fresh & Frozen Food",
  "Gambling Items",
  "Hand-to-Hand Combat Weapon",
  "Hazardous Waste",
  "Houses & Apartments",
  "Identity documents",
  "Jewelry & Personal Accessories",
  "Lighter",
  "Livestock",
  "Medical Textiles Product",
  "Money",
  "Motorbike & Scooter",
  "Mouthguards",
  "Office Space",
  "Oral Care Products",
  "Pet",
  "Pickup Truck",
  "Prescription Drugs & Medicine",
  "Prosthetic Equipments",
  "Rental Car",
  "Served Food",
  "Shoes & Footwear",
  "Socks & Hosiery",
  "Storage Unit & Locker",
  "Syringes & Needles",
  "Towels & Bathrobes",
  "Undergarments",
]);

// Enhanced keyword mapping for prohibited classes
const prohibitedKeywords: Record<string, string[]> = {
  Beverages: [
    "alcohol",
    "beer",
    "wine",
    "liquor",
    "drinks",
    "cocktail",
    "vodka",
    "whiskey",
    "rum",
    "gin",
    "tequila",
    "champagne",
    "brandy",
    "sake",
    "absinthe",
    "moonshine",
    "bourbon",
    "scotch",
    "cognac",
    "spirits",
    "alcoholic beverage",
    "malt liquor",
    "hard seltzer",
    "cider",
    "mead",
    "sangria",
    "beverage",
    "drink",
    "juice",
    "soda",
    "coffee",
    "tea",
    "energy drink",
    "soft drink",
    "water",
  ],

  "Bike & E-Bike": [
    "bike",
    "bicycle",
    "e-bike",
    "electric bike",
    "ebike",
    "cycling",
    "mountain bike",
    "road bike",
    "bmx",
    "hybrid bike",
    "cruiser bike",
    "folding bike",
    "recumbent bike",
    "tandem bike",
    "bike accessories",
    "bike parts",
    "cycling gear",
    "helmet",
    "bike lock",
    "bike rack",
  ],

  "Butane & LPG": [
    "butane",
    "lpg",
    "liquid petroleum gas",
    "propane",
    "gas cylinder",
    "gas tank",
    "fuel tank",
    "camping gas",
    "portable gas",
    "gas cartridge",
    "gas canister",
    "refill gas",
    "cooking gas",
  ],

  "Canned & Packaged Food": [
    "canned food",
    "packaged food",
    "processed food",
    "tinned food",
    "jarred food",
    "boxed food",
    "frozen meals",
    "ready meals",
    "instant food",
    "preserved food",
    "packaged snacks",
    "canned goods",
    "food packaging",
    "food containers",
    "meal kit",
    "food delivery",
    "groceries",
    "food items",
  ],

  "Cosmetics Products": [
    "cosmetics",
    "makeup",
    "beauty products",
    "skincare",
    "foundation",
    "lipstick",
    "mascara",
    "eyeshadow",
    "blush",
    "concealer",
    "powder",
    "primer",
    "eyeliner",
    "nail polish",
    "perfume",
    "cologne",
    "fragrance",
    "lotion",
    "cream",
    "serum",
    "moisturizer",
    "cleanser",
    "toner",
    "sunscreen",
    "anti-aging",
    "beauty tools",
    "makeup brushes",
    "beauty accessories",
  ],

  "Everyday Clothing": [
    "clothes",
    "clothing",
    "shirt",
    "pants",
    "dress",
    "jacket",
    "coat",
    "sweater",
    "hoodie",
    "t-shirt",
    "blouse",
    "skirt",
    "shorts",
    "jeans",
    "leggings",
    "suit",
    "tie",
    "scarf",
    "hat",
    "cap",
    "gloves",
    "mittens",
    "uniform",
    "costume",
    "formal wear",
    "casual wear",
    "sportswear",
    "activewear",
    "workout clothes",
    "fashion",
    "apparel",
    "garments",
    "outerwear",
    "innerwear",
  ],

  Explosive: [
    "explosive",
    "bomb",
    "dynamite",
    "grenade",
    "c4",
    "gunpowder",
    "fireworks",
    "pyrotechnics",
    "explosive device",
    "detonator",
    "blasting cap",
    "incendiary",
    "explosive materials",
    "military explosives",
    "commercial explosives",
    "mining explosives",
    "demolition explosives",
  ],

  Firearms: [
    "gun",
    "firearm",
    "pistol",
    "rifle",
    "shotgun",
    "revolver",
    "handgun",
    "assault rifle",
    "sniper rifle",
    "machine gun",
    "hunting rifle",
    "air gun",
    "pellet gun",
    "bb gun",
    "ammunition",
    "bullet",
    "cartridge",
    "magazine",
    "clip ammo",
    "scope sniper",
    "silencer",
    "suppressor",
    "gun parts",
    "gun accessories",
    "shooting equipment",
    "weapon",
    "combat weapon",
  ],

  "Fresh & Frozen Food": [
    "fresh food",
    "frozen food",
    "produce",
    "fruits",
    "vegetables",
    "meat",
    "poultry",
    "seafood",
    "fish",
    "dairy",
    "cheese",
    "milk",
    "bread",
    "bakery items",
    "organic food",
    "farm fresh",
    "local produce",
    "seasonal food",
    "raw food",
    "unprocessed food",
    "natural food",
    "whole food",
  ],

  "Gambling Items": [
    "gambling",
    "casino",
    "poker",
    "betting",
    "lottery",
    "scratch cards",
    "slot machine",
    "gambling equipment",
    "poker chips",
    "playing cards",
    "dice",
    "roulette",
    "blackjack",
    "bingo",
    "keno",
    "gaming chips",
    "casino tokens",
    "gambling accessories",
    "card shuffler",
  ],

  "Hand-to-Hand Combat Weapon": [
    "knife",
    "blade",
    "sword",
    "dagger",
    "machete",
    "combat knife",
    "throwing knife",
    "katana",
    "samurai sword",
    "martial arts weapons",
    "nunchucks",
    "brass knuckles",
    "knuckleduster",
    "baton",
    "club",
    "staff",
    "bo staff",
    "kendo stick",
    "fighting stick",
    "combat gear",
    "self-defense weapons",
    "tactical knife",
    "hunting knife",
    "survival knife",
  ],

  "Hazardous Waste": [
    "hazardous waste",
    "toxic waste",
    "chemical waste",
    "medical waste",
    "radioactive waste",
    "biohazard",
    "contaminated materials",
    "industrial waste",
    "electronic waste",
    "battery waste",
    "paint waste",
    "solvent waste",
    "asbestos",
    "lead paint",
    "mercury",
    "pcb",
    "dangerous materials",
  ],

  "Houses & Apartments": [
    "house",
    "apartment",
    "home",
    "property",
    "real estate",
    "residential property",
    "condo",
    "townhouse",
    "villa",
    "mansion",
    "cottage",
    "cabin",
    "studio",
    "loft",
    "penthouse",
    "duplex",
    "triplex",
    "housing",
    "accommodation",
    "dwelling",
    "residence",
  ],

  "Identity documents": [
    "passport",
    "id",
    "identity card",
    "driver's license",
    "license",
    "birth certificate",
    "social security card",
    "visa",
    "green card",
    "citizenship papers",
    "immigration documents",
    "government id",
    "student id",
    "employee id",
    "membership card",
    "permit",
    "certificate",
    "official documents",
    "legal documents",
    "identification",
    "personal documents",
  ],

  "Jewelry & Personal Accessories": [
    "jewelry",
    "necklace",
    "ring",
    "bracelet",
    "earrings",
    "watch",
    "pendant",
    "chain",
    "diamond",
    "gold",
    "silver",
    "platinum",
    "gemstone",
    "precious metals",
    "luxury accessories",
    "designer jewelry",
    "fashion accessories",
    "personal accessories",
    "decorative accessories",
  ],

  Lighter: [
    "lighter",
    "cigarette lighter",
    "butane lighter",
    "gas lighter",
    "electric lighter",
    "torch lighter",
    "windproof lighter",
    "refillable lighter",
    "disposable lighter",
    "lighter fluid",
    "lighter accessories",
    "smoking accessories",
    "fire starter",
  ],

  Livestock: [
    "livestock",
    "cattle",
    "cow",
    "bull",
    "pig",
    "hog",
    "goat",
    "sheep",
    "horse",
    "pony",
    "chicken",
    "rooster",
    "hen",
    "duck",
    "goose",
    "turkey",
    "farm animals",
    "breeding animals",
    "dairy animals",
    "meat animals",
    "poultry",
    "waterfowl",
    "barnyard animals",
  ],

  "Medical Textiles Product": [
    "medical textiles",
    "surgical gown",
    "medical mask",
    "surgical mask",
    "medical drape",
    "bandage",
    "gauze",
    "medical fabric",
    "hospital textiles",
    "patient gown",
    "scrubs",
    "medical uniform",
    "isolation gown",
    "protective clothing",
    "medical bedding",
    "hospital linen",
  ],

  Money: [
    "money",
    "cash",
    "currency",
    "banknotes",
    "bills",
    "coins",
    "dollars",
    "euros",
    "pesos",
    "cryptocurrency",
    "bitcoin",
    "digital currency",
    "foreign currency",
    "collectible coins",
    "rare coins",
    "precious metal coins",
    "legal tender",
    "monetary instruments",
  ],

  "Motorbike & Scooter": [
    "motorbike",
    "motorcycle",
    "scooter",
    "moped",
    "dirt bike",
    "sport bike",
    "cruiser motorcycle",
    "touring bike",
    "chopper",
    "bobber",
    "cafe racer",
    "electric scooter",
    "gas scooter",
    "vespa",
    "bike parts",
    "motorcycle accessories",
    "scooter parts",
    "two-wheeler",
  ],

  Mouthguards: [
    "mouthguard",
    "mouth guard",
    "dental guard",
    "night guard",
    "sports guard",
    "teeth protector",
    "dental appliance",
    "bite guard",
    "orthodontic appliance",
    "tmj guard",
    "custom mouthguard",
    "protective mouthpiece",
    "athletic mouthguard",
    "boxing mouthguard",
  ],

  "Office Space": [
    "office space",
    "commercial space",
    "business space",
    "coworking space",
    "shared office",
    "private office",
    "meeting room",
    "conference room",
    "workspace",
    "business center",
    "executive suite",
    "office rental",
    "commercial lease",
    "business premises",
  ],

  "Oral Care Products": [
    "oral care",
    "toothbrush",
    "toothpaste",
    "mouthwash",
    "dental floss",
    "teeth whitening",
    "dental care",
    "oral hygiene",
    "breath freshener",
    "tongue cleaner",
    "dental picks",
    "water flosser",
    "electric toothbrush",
    "dental rinse",
    "oral health products",
  ],

  Pet: [
    "pet",
    "dog",
    "cat",
    "puppy",
    "kitten",
    "bird",
    "fish",
    "reptile",
    "hamster",
    "guinea pig",
    "rabbit",
    "ferret",
    "chinchilla",
    "pet supplies",
    "pet accessories",
    "pet food",
    "pet toys",
    "aquarium fish",
    "tropical fish",
    "exotic pets",
    "small animals",
    "pet care",
    "pet services",
  ],

  "Pickup Truck": [
    "pickup truck",
    "pickup",
    "truck",
    "pickup vehicle",
    "utility truck",
    "work truck",
    "commercial truck",
    "heavy-duty truck",
    "light truck",
    "crew cab",
    "extended cab",
    "single cab",
    "4x4 truck",
    "diesel truck",
    "electric truck",
    "truck rental",
  ],

  "Prescription Drugs & Medicine": [
    "prescription drugs",
    "medicine",
    "medication",
    "pills",
    "tablets",
    "capsules",
    "pharmacy",
    "prescription medication",
    "controlled substances",
    "antibiotics",
    "painkillers",
    "insulin",
    "vaccines",
    "medical drugs",
    "pharmaceutical",
    "therapeutic drugs",
    "over-the-counter",
    "otc medication",
    "supplements",
    "vitamins",
    "herbal medicine",
    "homeopathic",
    "drug prescription",
  ],

  "Prosthetic Equipments": [
    "prosthetic",
    "prosthesis",
    "artificial limb",
    "prosthetic leg",
    "prosthetic arm",
    "prosthetic hand",
    "prosthetic foot",
    "medical prosthetics",
    "orthotic",
    "mobility aid",
    "assistive device",
    "rehabilitation equipment",
    "physical therapy equipment",
    "medical implant",
  ],

  "Rental Car": [
    "rental car",
    "car rental",
    "vehicle rental",
    "auto rental",
    "hire car",
    "lease car",
    "short-term rental",
    "daily rental",
    "weekly rental",
    "monthly rental",
    "economy car",
    "compact car",
    "luxury car rental",
    "suv rental",
    "van rental",
    "truck rental",
  ],

  "Served Food": [
    "served food",
    "prepared food",
    "cooked food",
    "restaurant food",
    "takeout",
    "delivery food",
    "catering",
    "meal service",
    "food service",
    "ready-to-eat",
    "hot food",
    "cold food",
    "buffet food",
    "banquet food",
    "event catering",
    "meal delivery",
    "food truck",
    "street food",
  ],

  "Shoes & Footwear": [
    "shoes",
    "footwear",
    "boots",
    "sneakers",
    "sandals",
    "heels",
    "flats",
    "loafers",
    "oxfords",
    "athletic shoes",
    "running shoes",
    "dress shoes",
    "casual shoes",
    "work boots",
    "hiking boots",
    "rain boots",
    "snow boots",
    "slippers",
    "flip-flops",
    "clogs",
    "moccasins",
    "espadrilles",
  ],

  "Socks & Hosiery": [
    "socks",
    "hosiery",
    "stockings",
    "pantyhose",
    "tights",
    "leggings",
    "compression socks",
    "athletic socks",
    "dress socks",
    "casual socks",
    "wool socks",
    "cotton socks",
    "ankle socks",
    "crew socks",
    "knee-high socks",
    "thigh-high socks",
    "no-show socks",
  ],

  "Storage Unit & Locker": [
    "storage unit",
    "locker",
    "storage space",
    "self storage",
    "mini storage",
    "storage facility",
    "storage rental",
    "storage container",
    "warehouse storage",
    "climate controlled storage",
    "personal storage",
    "business storage",
    "moving storage",
    "temporary storage",
  ],

  "Syringes & Needles": [
    "syringe",
    "needle",
    "injection",
    "medical syringe",
    "insulin syringe",
    "vaccine syringe",
    "hypodermic needle",
    "injection needle",
    "medical needle",
    "disposable syringe",
    "safety syringe",
    "auto-injector",
    "pen injector",
    "iv needle",
    "blood draw needle",
  ],

  "Towels & Bathrobes": [
    "towel",
    "bathrobe",
    "bath towel",
    "hand towel",
    "face towel",
    "beach towel",
    "gym towel",
    "kitchen towel",
    "dish towel",
    "washcloth",
    "robe",
    "dressing gown",
    "spa robe",
    "terry cloth",
    "microfiber towel",
    "bamboo towel",
    "linen towel",
  ],

  Undergarments: [
    "underwear",
    "undergarments",
    "bra",
    "panties",
    "boxers",
    "briefs",
    "lingerie",
    "intimates",
    "undershirt",
    "camisole",
    "slip",
    "shapewear",
    "compression garments",
    "thermal underwear",
    "long johns",
    "undies",
    "intimate apparel",
    "foundation garments",
    "support garments",
  ],

  Adult_Content: [
    "sex toys",
    "adult toys",
    "vibrator",
    "dildo",
    "sex doll",
    "adult entertainment",
    "pornography",
    "xxx",
    "erotic",
    "sexual services",
    "escort",
    "prostitution",
    "strip club",
    "massage parlor",
    "adult videos",
    "adult magazines",
    "fetish",
    "bdsm",
    "adult games",
    "sex shop",
    "adult store",
    "intimate products",
    "pleasure products",
  ],

  Illegal_Drugs: [
    "cocaine",
    "heroin",
    "methamphetamine",
    "meth",
    "crack",
    "ecstasy",
    "mdma",
    "lsd",
    "magic mushrooms",
    "psilocybin",
    "ketamine",
    "pcp",
    "dmt",
    "ayahuasca",
    "opium",
    "fentanyl",
    "synthetic drugs",
    "designer drugs",
    "research chemicals",
    "bath salts",
    "spice",
    "k2",
    "marijuana",
    "weed",
    "cannabis",
    "hash",
    "hashish",
    "thc",
    "edibles",
    "drug dealing",
    "drug trafficking",
    "illegal substances",
    "controlled substances",
    "narcotic",
    "stimulant",
    "depressant",
    "hallucinogen",
    "psychedelic",
  ],

  Tobacco_Vaping: [
    "cigarettes",
    "cigars",
    "tobacco",
    "chewing tobacco",
    "snuff",
    "nicotine",
    "vaping",
    "e-cigarettes",
    "vape",
    "vape juice",
    "e-liquid",
    "vape pen",
    "mod",
    "atomizer",
    "coils",
    "smoking accessories",
    "pipes",
    "bongs",
    "rolling papers",
    "cigarette papers",
    "hookah",
    "shisha",
    "water pipe",
    "smoking device",
    "tobacco products",
    "nicotine products",
  ],

  Human_Body_Parts: [
    "organs",
    "kidney",
    "liver",
    "heart",
    "lung",
    "brain",
    "blood",
    "plasma",
    "sperm",
    "eggs",
    "embryo",
    "tissue",
    "bone marrow",
    "stem cells",
    "body parts",
    "human remains",
    "cadaver",
    "corpse",
    "ashes",
    "cremated remains",
    "hair",
    "teeth",
    "fingernails",
    "skin",
    "body fluids",
    "urine",
    "saliva",
    "breast milk",
    "biological samples",
  ],

  Illegal_Services: [
    "hitman",
    "assassin",
    "murder for hire",
    "contract killing",
    "human trafficking",
    "organ trafficking",
    "drug trafficking",
    "money laundering",
    "fraud services",
    "fake documents",
    "forged documents",
    "identity theft",
    "credit card fraud",
    "hacking services",
    "ddos attack",
    "cyber attack",
    "illegal hacking",
    "phishing",
    "scam",
    "ponzi scheme",
    "pyramid scheme",
    "tax evasion",
    "insider trading",
  ],

  Inappropriate_Content: [
    "child exploitation",
    "underage",
    "minor",
    "pedophile",
    "child abuse",
    "bestiality",
    "animal abuse",
    "torture",
    "snuff",
    "gore",
    "extreme violence",
    "hate speech",
    "racist",
    "nazi",
    "terrorism",
    "terrorist",
    "extremist",
    "radical",
    "jihad",
    "isis",
    "al-qaeda",
    "bomb making",
    "assassination",
    "genocide",
    "ethnic cleansing",
  ],

  Stolen_Goods: [
    "stolen",
    "hot goods",
    "lifted",
    "shoplifted",
    "hijacked",
    "robbed",
    "burglarized",
    "stolen property",
    "stolen merchandise",
    "stolen electronics",
    "stolen jewelry",
    "stolen car",
    "stolen bike",
    "stolen phone",
    "stolen laptop",
    "fence",
    "fencing",
    "black market",
    "underground market",
    "illegal goods",
    "contraband",
    "smuggled",
  ],

  Counterfeit_Items: [
    "fake",
    "counterfeit",
    "replica",
    "knockoff",
    "imitation",
    "copy",
    "bootleg",
    "unauthorized",
    "pirated",
    "unlicensed",
    "trademark violation",
    "brand violation",
    "fake designer",
    "fake luxury",
    "fake electronics",
    "fake medication",
    "fake documents",
    "forged",
    "falsified",
    "duplicate",
    "clone",
    "reproduction",
  ],

  Disturbing_Content: [
    "suicide",
    "self harm",
    "cutting",
    "eating disorder",
    "anorexia",
    "bulimia",
    "pro-ana",
    "pro-mia",
    "self injury",
    "depression medication",
    "suicide methods",
    "harmful substances",
    "poison",
    "toxic chemicals",
    "dangerous experiments",
    "explosive making",
    "weapon making",
    "bomb instructions",
    "violence",
    "gore",
    "blood",
  ],

  Spam_Scam: [
    "get rich quick",
    "make money fast",
    "work from home scam",
    "pyramid scheme",
    "mlm scam",
    "ponzi",
    "nigerian prince",
    "lottery scam",
    "inheritance scam",
    "romance scam",
    "phishing",
    "fake lottery",
    "miracle cure",
    "weight loss scam",
    "investment scam",
    "forex scam",
    "crypto scam",
    "binary options",
    "guaranteed returns",
    "no risk investment",
    "free money",
    "easy money",
    "passive income scam",
  ],

  Inappropriate_Animals: [
    "exotic animals",
    "endangered species",
    "wild animals",
    "illegal pets",
    "venomous animals",
    "poisonous animals",
    "protected species",
    "rare animals",
    "animal fighting",
    "cockfighting",
    "dog fighting",
    "animal cruelty",
    "animal abuse",
    "illegal wildlife",
    "poaching",
    "ivory",
    "rhino horn",
    "tiger parts",
    "bear bile",
    "shark fin",
    "illegal animal products",
  ],

  Extremist_Content: [
    "white supremacy",
    "neo-nazi",
    "kkk",
    "hate group",
    "extremist",
    "terrorist organization",
    "radical ideology",
    "violent extremism",
    "domestic terrorism",
    "mass shooting",
    "school shooting",
    "bomb threat",
    "assassination plot",
    "political violence",
    "militia",
    "sovereign citizen",
    "anti-government",
    "conspiracy theory",
    "qanon",
  ],
};

const allowedClasses = [
  "Action Camera",
  "Adjustable Wrench",
  "Air Compressor",
  "Air Mover",
  "Angle Grinder",
  "Audio Mixer",
  "Axe",
  "Ball",
  "Belt Sander",
  "Bench Grinder",
  "Book",
  "Boom Microphone",
  "Bounce House",
  "Brad Nailer",
  "Camera Tripod",
  "Camping Cot",
  "Camping Tent",
  "Car Battery Charger",
  "Car Jack",
  "Car Polisher",
  "Caulking Gun",
  "Chainsaw",
  "Circular Saw",
  "Clamp Meter",
  "Claw Hammer",
  "Combination Square",
  "Combination Wrench Set",
  "Concrete Mixer",
  "Concrete Saw",
  "Cordless Drill",
  "Crimping Tool",
  "Crowbar",
  "DJ Controller",
  "DSLR camera",
  "Drain Auger",
  "Drone",
  "Drywall Screw Gun",
  "Drywall Trowel",
  "Dust Extractor",
  "Earth Auger",
  "Electric Hoist",
  "Electric Planer",
  "Electric ScrewDriver",
  "Engine Hoist",
  "Extension Cord Reel",
  "Extension Ladder",
  "Finishing Nailer",
  "Flathead Screwdriver Set",
  "Floor Polisher",
  "Floor Scraper",
  "Folding Camping Chair",
  "Folding Chairs",
  "Folding Tables",
  "Garden Rake",
  "Garden Tiller",
  "Gimbal Stabilizer",
  "Hacksaw",
  "Hammer Drill",
  "Hand Saw",
  "Hand Truck",
  "Hard Hat",
  "Headphone",
  "Heat Gun",
  "Heavy-Duty Fan",
  "Hedge Trimmer",
  "Hoe",
  "Impact Wrench",
  "Infrared Thermometer",
  "Jack Stands",
  "Jackhammer",
  "Jigsaw",
  "Ladder",
  "Laptop",
  "Laser Level",
  "Lavalier Microphone",
  "Lawn Mower",
  "Leaf Blower",
  "Loppers",
  "Metal Detector",
  "Metal Shears",
  "Microphone Stand",
  "Monitor",
  "Multimeter",
  "Needle Nose Pliers",
  "PEX Crimping Tool",
  "PVC Cutter",
  "Phillips Screwdriver Set",
  "Pickaxe",
  "Pipe Threader",
  "Pipe Wrench",
  "Pop-up Canopy Tent",
  "Portable Camping Stove",
  "Portable Cooler",
  "Portable Generator",
  "Portable Green Screen",
  "Post Hole Digger",
  "Power Trowel",
  "Pressure Washer",
  "Projector",
  "Projector Screen",
  "Putty Knife",
  "Rebar Cutter",
  "Ring Light",
  "Router Tool",
  "Rubber Mallet",
  "Scaffold Tower",
  "Scissor",
  "Shop Vacuum",
  "Shovel",
  "Sledgehammer",
  "Sleeping Bag",
  "Slip Joint Pliers",
  "Socket Wrench Set",
  "Sound System",
  "Spirit Level",
  "Steam Cleaner",
  "String Trimmer",
  "Stroller",
  "Studio Softbox Kit",
  "Tape Measure",
  "Thermal Camera",
  "Tin Snips",
  "Tire Inflator",
  "Tool Box",
  "Tool Chest",
  "Torque Wrench",
  "Torx Screwdriver Set",
  "Utility Knife",
  "Vacuum Cleaner",
  "Vise Grip",
  "Voltage Tester",
  "Wallpaper Steamer",
  "Water Pump",
  "Welding Clamps",
  "Welding Helmet",
  "Welding Machine",
  "Welding Table",
  "Wet Tile Saw",
  "Wire Strippers",
  "Wire Tracer",
  "Wireless Microphone Kit",
  "Wireless Speaker",
  "Wood Carving Kit",
  "Wood Hand Planer",
  "Work Light",
];

export function useProhibitedChecker() {
  const flatList = useMemo(() => {
    const list: string[] = [];
    Object.values(prohibitedKeywords).forEach((keywords) =>
      list.push(...keywords)
    );
    return list;
  }, []);

  function isProhibited(input: string): {
    prohibited: boolean;
    category?: string;
    matchedKeywords?: string[];
    similarity?: number;
    classMatch?: string;
  } {
    const normalized = input.toLowerCase().trim();
    const SIMILARITY_THRESHOLD = 0.8; // 80% similarity

    // Check direct class name matches first
    for (const className of prohibitedClasses) {
      const similarity = compareTwoStrings(normalized, className.toLowerCase());
      if (similarity >= SIMILARITY_THRESHOLD) {
        return {
          prohibited: true,
          category: className,
          classMatch: className,
          similarity,
        };
      }
    }

    // Check keyword matches
    for (const [category, keywords] of Object.entries(prohibitedKeywords)) {
      // Exact substring matches
      const exactMatches = keywords.filter((word) =>
        normalized.includes(word.toLowerCase())
      );
      if (exactMatches.length > 0) {
        return {
          prohibited: true,
          category,
          matchedKeywords: [...new Set(exactMatches)],
          similarity: 1.0,
        };
      }

      // Fuzzy matches
      for (const keyword of keywords) {
        const similarity = compareTwoStrings(normalized, keyword.toLowerCase());
        if (similarity >= SIMILARITY_THRESHOLD) {
          return {
            prohibited: true,
            category,
            matchedKeywords: [keyword],
            similarity,
          };
        }
      }
    }

    return { prohibited: false };
  }

  function isAllowedClass(className: string): boolean {
    return allowedClasses.includes(className);
  }

  function getProhibitedClasses(): string[] {
    return Array.from(prohibitedClasses);
  }

  function getAllowedClasses(): string[] {
    return [...allowedClasses];
  }

  function getCategoryKeywords(category: string): string[] {
    return prohibitedKeywords[category] || [];
  }

  function validateClassification(
    predictedClass: string,
    confidence: number = 0.8
  ): {
    allowed: boolean;
    prohibited: boolean;
    category?: string;
    confidence: number;
  } {
    const isProhibitedClass = prohibitedClasses.has(predictedClass);
    const isAllowedClassItem = allowedClasses.includes(predictedClass);

    return {
      allowed: isAllowedClassItem && confidence >= 0.8,
      prohibited: isProhibitedClass,
      category: isProhibitedClass ? predictedClass : undefined,
      confidence,
    };
  }

  return {
    isProhibited,
    isAllowedClass,
    prohibitedKeywords,
    flatList,
    getProhibitedClasses,
    getAllowedClasses,
    getCategoryKeywords,
    validateClassification,
    prohibitedClasses: Array.from(prohibitedClasses),
    allowedClasses,
  };
}
